# Generated by Django 5.0.1 on 2024-02-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('domicilio', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('cantidad_unidades', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('fecha_pago', models.DateField()),
                ('fecha_compra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('id_proveedor', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
                ('fecha_elav', models.DateField()),
                ('fecha_vence', models.DateField()),
                ('droga', models.CharField(max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proveedor', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('cuit', models.IntegerField()),
                ('domicilio', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('limite_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('cantidad_unidades', models.IntegerField()),
                ('min_unidades', models.IntegerField()),
            ],
        ),
    ]
